name: openph
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=24.0
  - openbabel=3.1.1
  - pymol-open-source=3.0.0
  - numpy=1.26
  - pip:
      - tqdm
      - torch==1.13.1
      - molvoxel==0.1.3
      - numba==0.59
      - omegaconf==2.3.0
      - gdown==5.1.0
      - biopython==1.83
