name: pmnet
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=24.0
  - openbabel=3.1.1
  - pymol-open-source=3.0.0
  - numpy=1.26.4
  - pip:
      - tqdm
      - molvoxel==0.1.3
      - numba==0.59.1
      - omegaconf==2.3.0
      - gdown==5.1.0
      - biopython==1.83
